const Map<String, dynamic> calcOperators = {
  "AC": "AC",
  "+/-": "toggleSign",
  "%": "percent",
  "÷": "divide",
  "7": "7",
  "8": "8",
  "9": "9",
  "x": "multiply",
  "4": "4",
  "5": "5",
  "6": "6",
  "-": "subtract",
  "1": "1",
  "2": "2",
  "3": "3",
  "+": "add",
  "0": {"label": "0", "span": 2},
  ".": "decimal",
  "=": "equals",
};